language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

install:
  - pip install .[performance]

script: 
  - make test
  - python tests/performance/performance_test.py --freq 20 --num-orders 500
